### ISSUE TITLE
fix css earphone page

### ISSUE THREAD

**Issue by kyerans** [swclabs/swipe#313]
![image](https://github.com/user-attachments/assets/20434938-a0ac-4d60-9391-615e577ae6dd)
Chỉnh css sản phẩm căn lề, chỉnh nút "mua hàng" tỉ lệ hợp lý, bỏ "So sánh tất cả các phiên bản Airpods", bỏ viền khung
tham khảo
![image](https://github.com/user-attachments/assets/1af4070a-e208-452a-aeac-c3e3516510b5)

**Comment by anthony2704** [comment]
I will fix this, please follow this branch: https://github.com/swclabs/swipe/pull/319
