### ISSUE TITLE
fix css shop/watch & /watch

### ISSUE THREAD

**Issue by kyerans** [swclabs/swipe#315]
- Kiểm tra cỡ chữ của header, section title cùng cỡ chữ thống nhất với các trang khác
- Sửa hiệu ứng tràn viền sản phẩm tương tự như #314 
- Tại trang /watch kiểm tra cỡ chữ và khoản cách giữa các sản phẩm phù hợp tránh bị thụt sâu quá so với các component khác
![image](https://github.com/user-attachments/assets/7be8ced8-c934-467a-98cf-a3b8169cc5b3)

- phần header làm phần nào thì hiển thị phần đó, tránh để quá nhiều không có trang tương ứng
![image](https://github.com/user-attachments/assets/70591d17-83fb-43e5-823c-17fd65e9fe35)

**Comment by anthony2704** [comment]
I will fix this, please follow this branch: https://github.com/swclabs/swipe/pull/320
