### ISSUE TITLE
fix css /accessories

### ISSUE THREAD

**Issue by kyerans** [swclabs/swipe#316]
- Căn lề trái phải của trang cho phù hợp với các trang khác
- Chỉnh lại cỡ chữ phù hợp cho đồng bộ với các trang khác
- Phần sản phẩm tạo hiệu ứng tràn viền tương tự như #314 
- Header, section title chỉnh cỡ chữ phù hợp với các trang khác

**Comment by anthony2704** [comment]
https://github.com/swclabs/swipe/pull/338
